wandb_version: 1

total_timesteps:
  desc: null
  value: 500000
policy_type:
  desc: null
  value: MlpPolicy
save_interval:
  desc: null
  value: 100000
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684780260.827617
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.15.2
      8:
      - 4
      - 5
