wandb_version: 1

run_name:
  desc: null
  value: SAC
env:
  desc: null
  value: CartPole-v0
episodes:
  desc: null
  value: 100
buffer_size:
  desc: null
  value: 100000
seed:
  desc: null
  value: 1
log_video:
  desc: null
  value: 0
save_every:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 256
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684160406.524184
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 2
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.15.2
      8:
      - 4
      - 5
